version: '3'
services:

  mysql:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: always
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    command:
      - --max_allowed_packet=1032505856
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    environment:
      TZ: "${TIMEZONE}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"

  smtp:
    image: namshi/smtp
    container_name: ${COMPOSE_PROJECT_NAME}-smtp
    restart: always
    environment:
      GMAIL_USER: "${GMAIL_USER}"
      GMAIL_PASSWORD: "${GMAIL_PASSWORD}"

  php-apache:
    build:
      context: ./images/php-apache
    container_name: ${COMPOSE_PROJECT_NAME}-php-apache
    restart: always
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ./config/vhost/default.conf:/etc/apache2/sites-available/000-default.conf:cached
    links:
    - 'mysql'
    environment:
      XDEBUG_CONFIG: remote_host=${REMOTE_HOST_XDEBUG}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    links:
    - 'mysql'
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${COMPOSE_PROJECT_NAME}-mysql
      PMA_PORT: ${PMA_PORT}

volumes:
  mysql-data:
