FROM amazonlinux:2.0.20200406.0
#MAINTAINER

# Install various utilities
RUN yum update -y && yum -y install nano ntp wget git net-tools epel-release traceroute gzip yum-utils zip unzip tar mysql which sendmail

RUN  yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum-config-manager --enable epel && yum install -y ssmtp mailx
COPY ssmtp/ssmtp.conf /etc/ssmtp/ssmtp.conf

# Install Apache
RUN yum -y install httpd && mv /etc/httpd/conf.d/welcome.conf  /etc/httpd/conf.d/welcome.conf_original

COPY vhosts/cms.conf /etc/httpd/conf.d/cms.conf

# Install PHP 7.3 and Config
RUN amazon-linux-extras install -y php7.3 \
&& yum -y clean metadata \
  && yum -y install php \
  && yum -y install php-opcache \
  && yum -y install php-mbstring \
  && yum -y install php-gd \
  && yum -y install php-xml \
  && yum -y install php-pear \
  && yum -y install php-fpm \
  && yum -y install php-pdo \
  && yum -y install php-devel \
  && yum -y install gcc \
  && yum -y install make \
&& sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 50M/g' /etc/php.ini \
&& sed -i 's/post_max_size = 8M/post_max_size = 64M/g' /etc/php.ini \
&& sed -i 's/memory_limit = 128M/memory_limit = 512M/g' /etc/php.ini \
&& sed -i 's/max_execution_time = 30/max_execution_time = 180/g' /etc/php.ini \
&& sed -i 's/max_input_vars = 1000/max_input_vars = 3000/g' /etc/php.ini \
&& sed -i 's/; max_input_vars = 3000/max_input_vars = 3000/g' /etc/php.ini \
&& sed -i 's/;date.timezone =/date.timezone = Europe\/Rome/g' /etc/php.ini

# Reconfigure Apache
RUN sed -i 's/AllowOverride None/AllowOverride All/g' /etc/httpd/conf/httpd.conf

## Install xdebug extension
RUN pecl channel-update pecl.php.net
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/lib64/php/modules/ -name xdebug.so)" >> /etc/php.ini \
    && echo "xdebug.start_with_request=yes" >> /etc/php.ini \
    && echo "xdebug.mode=debug" >> /etc/php.ini \
    && echo "xdebug.client_port=9003" >> /etc/php.ini \
    && echo "xdebug.idekey=PHPSTORM" >> /etc/php.ini

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php && \
  mv composer.phar /usr/local/bin/composer

# Install Drupal Console Launcher
RUN curl https://drupalconsole.com/installer -L -o drupal.phar && \
    mv drupal.phar /usr/local/bin/drupal && \
    chmod +x /usr/local/bin/drupal

# Install Drush Launcher
RUN curl https://github.com/drush-ops/drush-launcher/releases/download/0.9.1/drush.phar -L -o drush.phar && \
    mv drush.phar /usr/local/bin/drush && \
    chmod +x /usr/local/bin/drush

# Install AWS CLI v2
RUN curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip -o awscliv2.zip && \
    unzip awscliv2.zip && \
    ./aws/install

RUN echo 'alias ll="ls -al"' >> ~/.bashrc

EXPOSE 80
ENTRYPOINT ["/usr/sbin/httpd","-D","FOREGROUND"]
